2021-11-16 10:51:07,082 INFO    MainThread:13928 [wandb_setup.py:_flush():71] setting env: {}
2021-11-16 10:51:07,082 INFO    MainThread:13928 [wandb_setup.py:_flush():71] setting login settings: {}
2021-11-16 10:51:07,082 INFO    MainThread:13928 [wandb_init.py:_log_setup():357] Logging user logs to c:\Users\ruben\VDoomLearning\src\wandb\run-20211116_105107-2czywx9i\logs\debug.log
2021-11-16 10:51:07,082 INFO    MainThread:13928 [wandb_init.py:_log_setup():358] Logging internal logs to c:\Users\ruben\VDoomLearning\src\wandb\run-20211116_105107-2czywx9i\logs\debug-internal.log
2021-11-16 10:51:07,083 INFO    MainThread:13928 [wandb_init.py:_jupyter_setup():307] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000023693C8EA90>
2021-11-16 10:51:07,084 INFO    MainThread:13928 [wandb_init.py:init():390] calling init triggers
2021-11-16 10:51:07,084 INFO    MainThread:13928 [wandb_init.py:init():397] wandb.init called with sweep_config: {}
config: {}
2021-11-16 10:51:07,084 INFO    MainThread:13928 [wandb_init.py:init():435] starting backend
2021-11-16 10:51:07,084 INFO    MainThread:13928 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2021-11-16 10:51:07,087 INFO    MainThread:13928 [backend.py:ensure_launched():199] starting backend process...
2021-11-16 10:51:07,186 INFO    MainThread:13928 [backend.py:ensure_launched():205] started backend process with pid: 7148
2021-11-16 10:51:07,187 INFO    MainThread:13928 [wandb_init.py:init():444] backend started and connected
2021-11-16 10:51:07,202 INFO    MainThread:13928 [wandb_run.py:_label_probe_notebook():866] probe notebook
2021-11-16 10:51:07,203 INFO    MainThread:13928 [wandb_run.py:_label_probe_notebook():876] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-11-16 10:51:07,203 INFO    MainThread:13928 [wandb_init.py:init():503] updated telemetry
2021-11-16 10:51:07,254 INFO    MainThread:13928 [wandb_init.py:init():533] communicating current version
2021-11-16 10:51:10,518 INFO    MainThread:13928 [wandb_init.py:init():538] got version response 
2021-11-16 10:51:10,519 INFO    MainThread:13928 [wandb_init.py:init():548] communicating run to backend with 30 second timeout
2021-11-16 10:51:11,123 INFO    MainThread:13928 [wandb_init.py:init():576] starting run threads in backend
2021-11-16 10:51:11,368 INFO    MainThread:13928 [wandb_run.py:_console_start():1693] atexit reg
2021-11-16 10:51:11,369 INFO    MainThread:13928 [wandb_run.py:_redirect():1567] redirect: SettingsConsole.WRAP
2021-11-16 10:51:11,370 INFO    MainThread:13928 [wandb_run.py:_redirect():1604] Wrapping output streams.
2021-11-16 10:51:11,372 INFO    MainThread:13928 [wandb_run.py:_redirect():1628] Redirects installed.
2021-11-16 10:51:11,372 INFO    MainThread:13928 [wandb_init.py:init():603] run started, returning control to user process
2021-11-16 10:51:11,372 INFO    MainThread:13928 [wandb_run.py:_config_callback():911] config_cb None None {}
2021-11-16 11:53:41,369 INFO    MainThread:13928 [wandb_init.py:_pause_backend():270] pausing backend
2021-11-16 11:53:41,369 INFO    MainThread:13928 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-11-16 11:55:37,941 INFO    MainThread:13928 [wandb_init.py:_resume_backend():279] resuming backend
2021-11-16 11:56:15,901 INFO    MainThread:13928 [wandb_init.py:_pause_backend():270] pausing backend
2021-11-16 11:56:15,901 INFO    MainThread:13928 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-11-16 11:56:25,015 INFO    MainThread:13928 [wandb_init.py:_resume_backend():279] resuming backend
2021-11-16 11:56:25,025 INFO    MainThread:13928 [wandb_init.py:_pause_backend():270] pausing backend
2021-11-16 11:56:25,026 INFO    MainThread:13928 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-11-16 11:56:39,071 INFO    MainThread:13928 [wandb_init.py:_resume_backend():279] resuming backend
2021-11-16 11:56:39,082 INFO    MainThread:13928 [wandb_init.py:_pause_backend():270] pausing backend
2021-11-16 11:56:39,082 INFO    MainThread:13928 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-11-16 11:56:45,652 INFO    MainThread:13928 [wandb_init.py:_resume_backend():279] resuming backend
2021-11-16 11:56:45,664 INFO    MainThread:13928 [wandb_init.py:_pause_backend():270] pausing backend
2021-11-16 11:56:45,664 INFO    MainThread:13928 [jupyter.py:save_ipynb():374] not saving jupyter notebook
