2021-11-20 14:50:00,009 INFO    MainThread:21800 [wandb_setup.py:_flush():71] setting env: {}
2021-11-20 14:50:00,011 INFO    MainThread:21800 [wandb_setup.py:_flush():71] setting login settings: {}
2021-11-20 14:50:00,013 INFO    MainThread:21800 [wandb_init.py:_log_setup():357] Logging user logs to c:\vizdoom\vizdoom115pre\VDoomLearning-1\src\wandb\run-20211120_144959-1puuy1oa\logs\debug.log
2021-11-20 14:50:00,014 INFO    MainThread:21800 [wandb_init.py:_log_setup():358] Logging internal logs to c:\vizdoom\vizdoom115pre\VDoomLearning-1\src\wandb\run-20211120_144959-1puuy1oa\logs\debug-internal.log
2021-11-20 14:50:00,014 INFO    MainThread:21800 [wandb_init.py:_jupyter_setup():307] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000278712D4358>
2021-11-20 14:50:00,019 INFO    MainThread:21800 [wandb_init.py:init():390] calling init triggers
2021-11-20 14:50:00,019 INFO    MainThread:21800 [wandb_init.py:init():397] wandb.init called with sweep_config: {}
config: {}
2021-11-20 14:50:00,019 INFO    MainThread:21800 [wandb_init.py:init():435] starting backend
2021-11-20 14:50:00,020 INFO    MainThread:21800 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2021-11-20 14:50:00,037 INFO    MainThread:21800 [backend.py:ensure_launched():199] starting backend process...
2021-11-20 14:50:00,281 INFO    MainThread:21800 [backend.py:ensure_launched():205] started backend process with pid: 5292
2021-11-20 14:50:00,284 INFO    MainThread:21800 [wandb_init.py:init():444] backend started and connected
2021-11-20 14:50:00,311 INFO    MainThread:21800 [wandb_run.py:_label_probe_notebook():866] probe notebook
2021-11-20 14:50:00,312 INFO    MainThread:21800 [wandb_run.py:_label_probe_notebook():876] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-11-20 14:50:00,312 INFO    MainThread:21800 [wandb_init.py:init():503] updated telemetry
2021-11-20 14:50:00,317 INFO    MainThread:21800 [wandb_init.py:init():533] communicating current version
2021-11-20 14:50:05,326 INFO    MainThread:21800 [wandb_init.py:init():548] communicating run to backend with 30 second timeout
2021-11-20 14:50:09,238 INFO    MainThread:21800 [wandb_init.py:init():576] starting run threads in backend
2021-11-20 14:50:09,764 INFO    MainThread:21800 [wandb_run.py:_console_start():1693] atexit reg
2021-11-20 14:50:09,765 INFO    MainThread:21800 [wandb_run.py:_redirect():1567] redirect: SettingsConsole.WRAP
2021-11-20 14:50:09,765 INFO    MainThread:21800 [wandb_run.py:_redirect():1604] Wrapping output streams.
2021-11-20 14:50:09,781 INFO    MainThread:21800 [wandb_run.py:_redirect():1628] Redirects installed.
2021-11-20 14:50:09,782 INFO    MainThread:21800 [wandb_init.py:init():603] run started, returning control to user process
2021-11-20 14:50:09,782 INFO    MainThread:21800 [wandb_run.py:_config_callback():911] config_cb None None {}
2021-11-20 14:50:09,918 INFO    MainThread:21800 [wandb_init.py:_pause_backend():270] pausing backend
2021-11-20 14:50:09,921 INFO    MainThread:21800 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-11-20 14:51:56,333 INFO    MainThread:21800 [wandb_init.py:_resume_backend():279] resuming backend
2021-11-20 14:51:57,832 INFO    MainThread:21800 [wandb_run.py:_config_callback():911] config_cb None None {}
2021-11-20 14:52:34,763 INFO    MainThread:21800 [wandb_run.py:finish():1347] finishing run teccr/VDoomLearning/1puuy1oa
2021-11-20 14:52:34,764 INFO    MainThread:21800 [jupyter.py:save_history():429] not saving jupyter history
2021-11-20 14:52:34,764 INFO    MainThread:21800 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-11-20 14:52:34,764 INFO    MainThread:21800 [wandb_init.py:_jupyter_teardown():289] cleaning up jupyter logic
2021-11-20 14:52:34,764 INFO    MainThread:21800 [wandb_run.py:_atexit_cleanup():1663] got exitcode: 0
2021-11-20 14:52:34,766 INFO    MainThread:21800 [wandb_run.py:_restore():1635] restore
2021-11-20 14:52:35,358 INFO    MainThread:21800 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 864
  total_bytes: 864
}

2021-11-20 14:52:35,489 INFO    MainThread:21800 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 864
  total_bytes: 864
}

2021-11-20 14:52:35,841 INFO    MainThread:21800 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 864
  total_bytes: 864
}

2021-11-20 14:52:35,956 INFO    MainThread:21800 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 864
  total_bytes: 11663
}

2021-11-20 14:52:36,065 INFO    MainThread:21800 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 864
  total_bytes: 11663
}

2021-11-20 14:52:36,172 INFO    MainThread:21800 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 864
  total_bytes: 11663
}

2021-11-20 14:52:36,285 INFO    MainThread:21800 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 864
  total_bytes: 11663
}

2021-11-20 14:52:36,391 INFO    MainThread:21800 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 864
  total_bytes: 11663
}

2021-11-20 14:52:36,502 INFO    MainThread:21800 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 864
  total_bytes: 11663
}

2021-11-20 14:52:36,608 INFO    MainThread:21800 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1344
  total_bytes: 11663
}

2021-11-20 14:52:36,716 INFO    MainThread:21800 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11663
  total_bytes: 11663
}

2021-11-20 14:52:36,823 INFO    MainThread:21800 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11663
  total_bytes: 11663
}

2021-11-20 14:52:36,933 INFO    MainThread:21800 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11663
  total_bytes: 11663
}

2021-11-20 14:52:37,040 INFO    MainThread:21800 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11663
  total_bytes: 11663
}

2021-11-20 14:52:37,153 INFO    MainThread:21800 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11663
  total_bytes: 11663
}

2021-11-20 14:52:37,536 INFO    MainThread:21800 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11663
  total_bytes: 11663
}

2021-11-20 14:52:38,455 INFO    MainThread:21800 [wandb_run.py:_wait_for_finish():1793] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11663
  total_bytes: 11663
}
local_info {
}

2021-11-20 14:52:39,694 INFO    MainThread:21800 [wandb_run.py:_append_files():2061] logging synced files
